name: Enviar e-mail com PHPMailer

on:
  workflow_dispatch:  # Isso permite que você execute manualmente

jobs:
  enviar-email:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Instalar dependências
        run: composer install

      - name: Executar o script de envio
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: php email.php
